# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Ray
tagline:          'UCLA CS'
description:      'CS & Math Stuff'
url:              http://oneraynyday.github.io
baseurl:          ''

author:
  name:           'Ray Zhang'

paginate:         5     

# Custom vars
version:          2.1.0

github:           https://github.com/oneraynyday
