# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Ray
tagline:          'UCLA CS'
description:      'UCLA CS. ML. Math. Algorithms.'
url:              http://oneraynyday.github.io
baseurl:          ''

author:
  name:           'Ray Zhang'
  url:            https://github.com/oneraynyday

paginate:         5

# Custom vars
version:          2.1.0

github:           https://github.com/oneraynyday
